---
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: 04:47
    reviewers:
      - agarzola
    assignees:
      - agarzola
    versioning-strategy: auto
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: 04:47
    reviewers:
      - agarzola
    assignees:
      - agarzola
